---
title: "TOUCH-BRAIN: Pre-Registration Plan"
author: "Phuc TU Nguyen"
date: "2025-06-06"

output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc: true
    toc_depth: 3
    number_sections: true
    collapse: true
---

```{r setup, warning=FALSE, echo=FALSE, message=FALSE}
## Set up libraries and define paths with function

rm(list = ls())
library(rstudioapi)

script_path <- dirname(rstudioapi::getActiveDocumentContext()$path)
function_path <- file.path(script_path, "function")

source(file.path(function_path, "loadconfig.R"))
load_lib()
load_path(script_path)
load_palette()

vps <- c("P")
```


# Pool data {.hidden .unlisted}
<font size="1"> Behavioral and EEG data are merged across all participants and blocks. Block number and trial number are assigned per condition (t/m &times; a/p &times; unimodal/both) </font>

```{r warning=FALSE, message=FALSE, echo=FALSE}
source(file.path(function_path, "loaddata.R"))


# EEG ----

eeg_data <- load_eegdata(vps, file.path(pathlist$eeg_data_path, "BigEpoch_OneSecPhase"))
# Adjustment according to protocol
{
  empty_row <- eeg_data[1, ]
  empty_row[1, ] <- NA

  empty_row$filename <- "P23_move_active_results.xls"
  eeg_data <- rbind(
    eeg_data[1:(which(eeg_data$filename == "P23_move_active_results.xlsx")[36]), ],
    empty_row,
    eeg_data[(which(eeg_data$filename == "P23_move_active_results.xlsx")[37]):nrow(eeg_data), ]
  )
  eeg_data <- eeg_data[-which(eeg_data$filename == "P23_move_passive_results.xlsx")[51], ]
}
eeg_OneSecPhase <- adjust_eeg_df(eeg_data)
##############################################################

eeg_data <- load_eegdata(vps, file.path(pathlist$eeg_data_path, "Revise_5Phase")) 
# Adjustment according to protocol
{
  empty_row <- eeg_data[1, ]
  empty_row[1, ] <- NA

  empty_row$filename <- "P23_move_active_results.xls"
  eeg_data <- rbind(
    eeg_data[1:(which(eeg_data$filename == "P23_move_active_results.xlsx")[36]), ],
    empty_row,
    eeg_data[(which(eeg_data$filename == "P23_move_active_results.xlsx")[37]):nrow(eeg_data), ]
  )
  eeg_data <- eeg_data[-which(eeg_data$filename == "P23_move_passive_results.xlsx")[51], ]
}
eeg_5Phase <- adjust_eeg_df(eeg_data)
###################################################
eeg_data <- left_join(eeg_5Phase, eeg_OneSecPhase, by=c("filename", "NAME", "QUESTION", "ACTIVE", "unimodal", "trial_number")) %>%
  mutate(MovDur.x = round(MovDur.x,2),
         MovDur.y = round(MovDur.y/1000,2))%>%
  mutate(movdur.diff = abs(MovDur.x - MovDur.y), .before = MovDur.x)

############################
# Check movement duration
ggplot(eeg_data)+
  geom_point(aes(x=MovDur.x, y=MovDur.y))+
  labs(x="Trial-specific analysis", y="Same-length epoching")

```


## Load and preprocess raw data 
```{r warning=FALSE, message=FALSE, echo=FALSE}
xlsx_name <- format(Sys.time(), "BEH_EEG_Data_%d%m%Y.xlsx")
source(file.path(function_path, "preprocessdata.R"))
# channels <- expand.grid(c("F", "Fc", "FC", "C", "CP", "P"), c("3", "5", "z", "4", "6"))
rawData <- read_excel(path = file.path(pathlist$result_path, xlsx_name))
rawData <- preprocess_beh_df(rawData) %>%
  select(
    sbjN, trialN, task, mov, unimodal, condN, BLOCK, trial_number, DURATION, MovDur, HalfDur,
  )

rawData$rowid = rownames(rawData) %>% as.numeric()

ggplot(rawData)+
  geom_line(aes(x = rowid, y = DURATION), color = 'red')+
  geom_line(aes(x = rowid, y = MovDur), color = 'green')+
  geom_line(aes(x = rowid, y = HalfDur), color = 'blue')


```

